Team1LUSS/Models/Supplier.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1LUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.ItemSuppliers = new HashSet<ItemSupplier>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }
    
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Fax { get; set; }
        public string GSTRNo { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSupplier> ItemSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
    }
}

Team1LUSS/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Team1LUSS.Models;

namespace Team1LUSS.Controllers
{
    public class SupplierController : Controller
    {
        // GET: Supplier
        //Reuben
        public ActionResult SupplierList()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            //if (e.RoleID < 3)
            //{
            //    return RedirectToAction("NotAuthorized");
            //}
            //EVERYPAGE

            ViewBag.user = e;
            ViewBag.SupplierList = new BusinessLogic().GetSuppliers;
            return View();
        }

        //Reuben
        public ActionResult SupplierCard()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            //if (e.RoleID < 3)
            //{
            //    return RedirectToAction("NotAuthorized");
            //}
            //EVERYPAGE

            string sid = Request.QueryString["SuppID"];
            ViewBag.user = e;
            ViewBag.Aitems = new BusinessLogic().GetAItemsBySupplier(sid);
            ViewBag.Bitems = new BusinessLogic().GetBItemsBySupplier(sid);
            ViewBag.Citems = new BusinessLogic().GetCItemsBySupplier(sid);
            ViewBag.Allitems = new BusinessLogic().GetAllItemsBySupplier(sid);
            return View();
        }
    }
}

Team1LUSS/Views/Supplier/SupplierCard.cshtml
@{
    ViewBag.Title = "Supplier Card";
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="../../plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>

<body class="theme-blue">
    @Html.Partial("_NavBar")
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <ol class="breadcrumb">
                    <li><a href="../../Home/SupplierList">Suppliers</a></li>
                    <li class="active">@ViewBag.Allitems[0].SupplierID</li>
                </ol>
            </div>

            <!-- Hover Rows -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Supplier Card
                            </h2>
                            <p>
                                <br>
                                Supplier Name: @ViewBag.Allitems[0].Supplier.SupplierName<br>
                                Contact Name: @ViewBag.Allitems[0].Supplier.ContactName<br>
                                Email: @ViewBag.Allitems[0].Supplier.Email<br>
                                Phone: @ViewBag.Allitems[0].Supplier.Phone<br>
                                Fax: @ViewBag.Allitems[0].Supplier.Fax<br>
                                Address: @ViewBag.Allitems[0].Supplier.Address<br>
                            </p>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Print Supplier Card</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body table-responsive">
                            <h4>
                                Supplied Items<br />
                                <small>All items listed by rank:</small>
                            </h4>
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>RANK</th>
                                        <th>ITEM CODE</th>
                                        <th>ITEM DESCRIPTION</th>
                                        <th>UNIT OF MEASUREMENT</th>
                                        <th>STOCK CARD</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var a in ViewBag.Aitems)
                                    {
                                        <tr>
                                            <td>A</td>
                                            <td>@a.ItemCode</td>
                                            <td>@a.Catalogue.Description</td>
                                            <td>@a.Catalogue.UnitofMeasure</td>
                                            <td><a href="@Url.Action("StockCard", "Inventory")?ItemCode=@a.ItemCode">Details</a></td>
                                        </tr>
                                    }
                                    @foreach (var b in ViewBag.Bitems)
                                    {
                                        <tr>
                                            <td>B</td>
                                            <td>@b.ItemCode</td>
                                            <td>@b.Catalogue.Description</td>
                                            <td>@b.Catalogue.UnitofMeasure</td>
                                            <td><a href="@Url.Action("StockCard", "Inventory")?ItemCode=@b.ItemCode">Details</a></td>
                                        </tr>
                                    }
                                    @foreach (var c in ViewBag.Citems)
                                    {
                                        <tr>
                                            <td>C</td>
                                            <td>@c.ItemCode</td>
                                            <td>@c.Catalogue.Description</td>
                                            <td>@c.Catalogue.UnitofMeasure</td>
                                            <td><a href="@Url.Action("StockCard", "Inventory")?ItemCode=@c.ItemCode">Details</a></td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Hover Rows -->

        </div>
    </section>

    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="../../plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="../../plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <script src="../../js/pages/tables/jquery-datatable.js"></script>

    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>
</body>

</html>

Team1LUSS/Views/Supplier/SupplierList.cshtml
@{
    ViewBag.Title = "Suppliers";
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="../../plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>

<body class="theme-blue">
    @Html.Partial("_NavBar")
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <!-- <h2>Catalogue</h2> -->
            </div>
            <!-- Catalogue -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Suppliers
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>Supplier ID</th>
                                            <th>Supplier Name</th>
                                            <th>Contact NAME</th>
                                            <th>Email</th>
                                            <th>Phone</th>
                                            <th>Fax</th>
                                            <th>GSTR NO</th>
                                            <th>Address</th>
                                            <th>Details</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var i in ViewBag.SupplierList)
                                        {
                                            <tr>
                                                <td>@i.SupplierID</td>
                                                <td>@i.SupplierName</td>
                                                <td>@i.ContactName</td>
                                                <td>@i.Email</td>
                                                <td>@i.Phone</td>
                                                <td>@i.Fax</td>
                                                <td>@i.GSTRNo</td>
                                                <td>@i.Address</td>
                                                <td><a href="@Url.Action("SupplierCard", "Supplier")?SuppID=@i.SupplierID">Details</a></td>
                                                @*<td><a href="./SupplierCard?SuppID=@i.SupplierID">Details</a></td>*@
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Catalogue -->
        </div>
    </section>

    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="../../plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="../../plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <script src="../../js/pages/tables/jquery-datatable.js"></script>

    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>
</body>

</html>