Team1LUSS/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using Team1LUSS.Models;

namespace Team1LUSS.Controllers
{
    public class PurchaseController : Controller
    {
        // GET: Purchase
        //Luowei
        //static String testm;
        public ActionResult OrderDetails()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID < 3)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            ViewBag.slist = BusinessLogic.GetSuplierListInPO();

            int intgetid = Convert.ToInt32(this.Request.QueryString["arid"]);
            if (this.Request.QueryString["arid"] != null)
            {
                ViewBag.slist = BusinessLogic.GetSuplierListInPOByID(intgetid);
            }

            ViewBag.po = BusinessLogic.getPurchaseOrderID(intgetid);

            ViewBag.odlist = BusinessLogic.listorderdetails(intgetid);

            List<SubTotal> sublist = new List<SubTotal>();

            List<PurchaseOrderDetail> polist = BusinessLogic.listorderdetails(intgetid);

            SubTotal sub;
            List<Supplier> supplierlist = BusinessLogic.getSupplierlist();
            foreach (var item in supplierlist)
            {
                sub = new SubTotal(item.SupplierID);
                sublist.Add(sub);
            }
            foreach (var item in polist)
            {
                foreach (var i in sublist)
                {
                    if (item.Supplier == i.SupplierName)
                    {
                        i.Stotal = i.Stotal + Convert.ToDouble(item.Qty) * Convert.ToInt32(item.Catalogue.AveragePrice);
                    }
                }
            }
            double gtotal = 0;
            foreach (var i in sublist)
            {
                gtotal = gtotal + i.Stotal;
            }

            ViewBag.gtotal = gtotal;
            ViewBag.subtotal = sublist;
            return View();
        }
        //Luowei
        public ActionResult OrderApproval()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID < 3)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            ViewBag.olist = BusinessLogic.listorder();
            ViewBag.oplist = BusinessLogic.listpendingorder();
            ViewBag.polistbyemployee = BusinessLogic.listapprovedorderbyEmployee(e.EmployeeID);
            ViewBag.popendinglistbyemployee = BusinessLogic.listpendingorderbyEmployee(e.EmployeeID);
            return View();
        }
        //Luowei
        public ActionResult PendingApprovalOrderDetails()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID < 3)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            ViewBag.slist = BusinessLogic.GetSuplierListInPO();

            int intgetid = Convert.ToInt32(this.Request.QueryString["oid"]);
            if (this.Request.QueryString["oid"] != null)
            {
                ViewBag.slist = BusinessLogic.GetSuplierListInPOByID(intgetid);

            }
            ViewBag.po = BusinessLogic.getPurchaseOrderID(intgetid);

            ViewBag.odlist = BusinessLogic.listorderdetails(intgetid);

            List<SubTotal> sublist = new List<SubTotal>();

            List<PurchaseOrderDetail> polist = BusinessLogic.listorderdetails(intgetid);

            SubTotal sub;
            List<Supplier> supplierlist = BusinessLogic.getSupplierlist();
            foreach (var item in supplierlist)
            {
                sub = new SubTotal(item.SupplierID);
                sublist.Add(sub);
            }
            foreach (var item in polist)
            {
                foreach (var i in sublist)
                {
                    if (item.Supplier == i.SupplierName)
                    {
                        i.Stotal = i.Stotal + Convert.ToDouble(item.Qty) * Convert.ToInt32(item.Catalogue.AveragePrice);
                    }
                }
            }
            double gtotal = 0;
            foreach (var i in sublist)
            {
                gtotal = gtotal + i.Stotal;
            }
            ViewBag.gtotal = gtotal;
            ViewBag.subtotal = sublist;
            return View();
        }
        //Luowei
        public ActionResult Approved()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID < 4)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            string s = this.Request.QueryString["approvedpoid"];
            int intapprovedpoid = Convert.ToInt32(this.Request.QueryString["approvedpoid"]);
            if (s != null)
            {
                using (TransactionScope ts = new TransactionScope())
                {
                    BusinessLogic.setApprovedPO(intapprovedpoid, e.EmployeeID);
                    BusinessLogic.UpdateStockCardAndCatalogue(intapprovedpoid);
                    ts.Complete();
                }

            }
            return View();
        }
        //Luowei
        public ActionResult Rejected()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID < 4)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            string s = this.Request.QueryString["rejectedpoid"];
            int intrejectedpoid = Convert.ToInt32(this.Request.QueryString["rejectedpoid"]);
            if (s != null)
            {
                BusinessLogic.setRejectedPO(intrejectedpoid, e.EmployeeID);
            }
            return View();
        }

        //Irene
        public ActionResult EditPurchaseOrder()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID != 3)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            String s = Request.Form["items"];
            List<Catalogue> clist = new List<Catalogue>();
            List<ItemSupplier> slist = new List<ItemSupplier>();

            if (s != null)
            {
                Catalogue c;                
                
                foreach (var selection in s.Split(','))
                {
                    c = BusinessLogic.getCatalogueByID(selection);
                    clist.Add(c);
                }

                ItemSupplier itemSupplier;
                String rank1 = "A";
                String rank2 = "B";
                String rank3 = "C";
                
                foreach (var selection in s.Split(','))
                {
                    
                        itemSupplier = BusinessLogic.getItemSupplierByID(selection, rank1);
                        slist.Add(itemSupplier);
                        itemSupplier = BusinessLogic.getItemSupplierByID(selection, rank2);
                        slist.Add(itemSupplier);
                        itemSupplier = BusinessLogic.getItemSupplierByID(selection, rank3);
                        slist.Add(itemSupplier);
                    
                }
            }
            ViewBag.clist = clist;            
            ViewBag.slist = slist;
            return View();
        }        
        //Irene
        public ActionResult CreatePurchaseOrder()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID != 3)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            String s = Request.Form["items"];
            if (s != null)
            {
                decimal amount = 0;
                int QtyNo = Request.Form["qty"].Split(',').Count();
                Response.Write(QtyNo);
                
                int oid = BusinessLogic.AddItem(e.EmployeeID);
                for (int i = 0; i < QtyNo; i++)
                {
                    if (Convert.ToInt32(Request.Form["qty"].Split(',')[i]) > 0)
                    {
                        BusinessLogic.AddItemDetail(oid, Request.Form["supplier"].Split(',')[i], s.Split(',')[i], Convert.ToInt32(Request.Form["qty"].Split(',')[i]));
                    }
                    amount = amount + Convert.ToInt32(Request.Form["qty"].Split(',')[i]) * Convert.ToDecimal(BusinessLogic.getCatalogueByID(s.Split(',')[i]).AveragePrice);
                }
                BusinessLogic.UpdateAmountByID(oid, amount);

            }
            ViewBag.amount = s;
            ViewBag.olist = BusinessLogic.GetOrderCatalogue();

            return View();
        }

Team1LUSS/Views/Purchase/Approved.cshtml
@{
    ViewBag.Title = "Approved Order";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />
    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />
    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">
    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>
<body class="theme-blue">
    @Html.Partial("_NavBar")
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>Purchase order is approved.</h2>
                <form action="./OrderApproval" method="post">
                    <br />
                    <a href="./OrderApproval" button type="button" class="btn btn-default waves-effect" style="width:100px">Back to List</a>
                </form>
            </div>
        </div>
    </section>
    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>
    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>
    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>
    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>
</body>
</html>

Team1LUSS/Views/Purchase/CreatePurchaseOrder.cshtml
@{
    ViewBag.Title = "Create Purchase Order";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />
    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />
    <!-- JQuery DataTable Css -->
    <link href="../../plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">
    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>
<body class="theme-blue">   
    @Html.Partial("_NavBar") 
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>Purchase Order @ViewBag.amount</h2>
            </div>
            <form action="@Url.Action("EditPurchaseOrder", "Purchase")" method="post">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="card">
                            <div class="header">
                                <h2>
                                    Order Catalogue
                                </h2>
                            </div>

                            <div class="body">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                        <thead>
                                            <tr>
                                                <th>Item #</th>
                                                <th>Category</th>
                                                <th>Description</th>
                                                <th>Reorder Level</th>
                                                <th>Current Qty</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr>
                                                <th>Item #</th>
                                                <th>Category</th>
                                                <th>Description</th>
                                                <th>Reorder Level</th>
                                                <th>Current Qty</th>
                                                <th></th>
                                            </tr>
                                        </tfoot>
                                        <tbody>
                                            @for (var i = 0; i < ViewBag.olist.Count; i++)
                                            {
                                                <tr>
                                                    <td>@ViewBag.olist[i].ItemCode</td>
                                                    <td>@ViewBag.olist[i].Category.CategoryName</td>
                                                    <td>@ViewBag.olist[i].Description</td>
                                                    <td>@ViewBag.olist[i].ReorderLevel</td>
                                                    <td>@ViewBag.olist[i].CurrentStockQty</td>
                                                    <td>
                                                        <input type="checkbox" id="md_checkbox_@ViewBag.olist[i].ItemCode" class="chk-col-blue" value="@ViewBag.olist[i].ItemCode" name="items" />
                                                        <label for="md_checkbox_@ViewBag.olist[i].ItemCode"></label>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                 <div align="right"><button type="submit" class="btn btn-primary waves-effect" name="order">Order Items</button></div><br />
            </form>
            <!-- #END# Basic Examples -->
        </div>
    </section>
    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>
    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>
    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>
    <!-- Jquery DataTable Plugin Js -->
    <script src="../../plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="../../plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <script src="../../js/pages/tables/jquery-datatable.js"></script>
    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>
</body>
</html>

Team1LUSS/Views/Purchase/EditPurchaseOrder.cshtml
@{
    ViewBag.Title = "Order Details";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />
    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />
    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">
    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>
<body class="theme-blue">
    @Html.Partial("_NavBar")
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>Reorder</h2>
            </div>
            <!-- Basic Table -->
            <form action="./CreatePurchaseOrder" onsubmit="return changeText()" method="post">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="card">
                            <div class="body table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Item #</th>
                                            <th>Description</th>
                                            <th>Suppliers</th>
                                            <th>Quantity</th>
                                        </tr>
                                    </thead>
                                    <tbody>                                        
                                        @for (int i = 0; i < ViewBag.clist.Count; i++)
                                        {
                                            for (var j = 0; j < ViewBag.slist.Count; j++)
                                            {
                                                if (ViewBag.clist[i].ItemCode == ViewBag.slist[j].ItemCode)
                                                {
                                                    <tr>
                                                        @if (j % 3 == 0)
                                                        {
                                                            <th scope="row">@ViewBag.clist[i].ItemCode <input type="hidden" class="miniqty" value="@ViewBag.clist[i].ReorderMinQty" /></th>
                                                            <td>@ViewBag.clist[i].Description</td>
                                                        }
                                                        else
                                                        {
                                                            <th></th>
                                                            <td></td>
                                                        }


                                                        @if (ViewBag.clist[i].ItemCode == ViewBag.slist[j].ItemCode)
                                                        {
                                                            <td>
                                                                @ViewBag.slist[j].SupplierID
                                                                <input type="hidden" name="items" value="@ViewBag.clist[i].ItemCode" />
                                                                <input type="hidden" name="supplier" value="@ViewBag.slist[j].SupplierID" />
                                                            </td>
                                                            <td>
                                                                @if (j % 3== 0)
                                                                {
                                                                    <input type="text" class="form-control @j" name="qty" value="@ViewBag.clist[i].ReorderMinQty">
                                                                }
                                                                else
                                                                {
                                                                    <input type="text" class="form-control @j" name="qty" value="0">
                                                                }
                                                            </td>
                                                        }
                                                    </tr>
                                                }
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div align ="right"><button type="submit" class="btn btn-primary waves-effect" name="submitorder">Submit Order</button></div><br />
                </div>
            </form>
            <!-- #END# Basic Table -->
        </div>
    </section>
    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>
    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>
    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>
    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <script>
        function changeText() {
            for (var i = 0; i < @ViewBag.clist.Count; i++) {                
                if (document.getElementsByClassName('miniqty')[i].value * 1 >( document.getElementsByClassName('0')[i].value * 1 + document.getElementsByClassName('1')[i].value * 1 + document.getElementsByClassName('2')[i].value * 1))
                {  alert("Cannot less than "+document.getElementsByClassName('miniqty')[i].value);
                document.getElementsByClassName('0')[i].value = "Cannot less than "+document.getElementsByClassName('miniqty')[i].value;
                document.getElementsByClassName('1')[i].value = "Cannot less than "+document.getElementsByClassName('miniqty')[i].value;
                    return false;}
                else
                {}
            }
        }
    </script>
    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>

</body>
</html>

Team1LUSS/Views/Purchase/Rejected.cshtml
@{
    ViewBag.Title = "Rejected Order";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />
    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />
    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">
    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>
<body class="theme-blue">
    @Html.Partial("_NavBar")
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>Purchase order is rejected.</h2>
                <form action="./OrderApproval" method="post">
                    <br />
                    <button type="submit" class="btn btn-default waves-effect" role="button" style="width:100px">Back to List</button>
                </form>
            </div>
        </div>
    </section>
    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>
    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>
    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>
    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>
</body>
</html>