Team1LUSS/Models/Requisition.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1LUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisition()
        {
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
        }
    
        public int RequisitionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> AuthorizedBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
    }
}

Team1LUSS/Controllers/RequisitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using Team1LUSS.Models;

namespace Team1LUSS.Controllers
{
    public class RequisitionController : Controller
    {
        // GET: Requisition
        //Reuben
        public ActionResult DeptHeadReqMain()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID != 2 && e.Authorization != "Authorized")
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            string c = Request.Form["description"];
            string s = Request.Form["approval"];
            string id = Request.Form["rid"];
            int rid = Convert.ToInt32(id);
            int aid = e.EmployeeID;
            if (s == "Approved")
            {
                //BusinessLogic.UpdateRequsitionByID(rid, aid, DateTime.Now, s, c);
                using (TransactionScope ts = new TransactionScope())
                {
                    BusinessLogic.UpdateRequsitionByID(rid, aid, DateTime.Now, s, c);
                    BusinessLogic.UpdateInterimQtyFromReq(rid);

                    //For Email notification
                    Requisition r = BusinessLogic.getRequisitionByID(rid);
                    Employee emp = BusinessLogic.getEmployeeByID((int)r.EmployeeID);
                    Email email;
                    String emailaddress;
                    string emailname;
                    String bodytext;
                    String subject = "Requisition Approval Status";

                    emailaddress = emp.EmailAdd;
                    emailname = emp.EmployeeName;
                    bodytext = "Dear " + emailname + ",<br /><br />" + "Your requisition has been approved by " + e.EmployeeName + ".<br /><br /><br /><br />================================================================<br /><br />This is a system generated email, Please do not reply. <br /><br />Store Administrator";
                    email = new Email(emailaddress, subject, bodytext);
                    BusinessLogic.SendEmail(email);

                    ts.Complete();
                }
            }
            if (s == "Rejected")
            {
                BusinessLogic.UpdateRequsitionByID(rid, aid, DateTime.Now, s, c);

                //For Email notification
                Requisition r = BusinessLogic.getRequisitionByID(rid);
                Employee emp = BusinessLogic.getEmployeeByID((int)r.EmployeeID);
                Email email;
                String emailaddress;
                string emailname;
                String bodytext;
                String subject = "Requisition Approval Status";

                emailaddress = emp.EmailAdd;
                emailname = emp.EmployeeName;
                bodytext = "Dear " + emailname + ",<br /><br />" + "Your requisition has been rejected by " + e.EmployeeName + ".<br /><br /><br /><br />================================================================<br /><br />This is a system generated email, Please do not reply. <br /><br />Store Administrator";
                email = new Email(emailaddress, subject, bodytext);
                BusinessLogic.SendEmail(email);
            }
            ViewBag.PendingList = new BusinessLogic().GetPendingReqs(e.DepartmentID);
            ViewBag.ApprovedList = new BusinessLogic().GetAllOtherReqs(e.DepartmentID);
            return View();
        }
        //Reuben
        public ActionResult DeptHeadReqPending(int id)
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID != 2 && e.Authorization != "Authorized")
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            ViewBag.ReqDetails = new BusinessLogic().GetRequisitionDetails(id);
            ViewBag.ReqID = id;
            return View();
        }
        //Reuben
        public ActionResult DeptHeadReqDetails(int id)
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID != 2 && e.Authorization != "Authorized")
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            ViewBag.ReqDetails = new BusinessLogic().GetRequisitionDetails(id);
            return View();
        }

        //Sandor
        public ActionResult EmployeeReq()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID != 1)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE

            ViewBag.user = e;
            //list requisition
            String s = Request.Form["name1"];

            List<int> ridlist = new List<int>();

            if (s != null)
            {
                foreach (var item in s.Split(','))
                {
                    int id = Convert.ToInt32(item);
                    BusinessLogic.deleteReqListDetail(id);
                    BusinessLogic.deleteReqList(id);
                }
            }
            //End list

            //Create requisition
            String i = Request.Form["Item"];

            if (i != null)
            {
                String[] itemarr = i.Split(',');

                BusinessLogic.createRequisition(e.EmployeeID);

                int reqID = BusinessLogic.getBottomRequisitionID();


                for (int j = 0; j < itemarr.Length; j++)
                {
                    String qty = Request.Form[itemarr[j]];
                    int Qty = Convert.ToInt16(qty);

                    BusinessLogic.createRequisitionDetail(reqID, itemarr[j], Qty);

                }

                //For Email notification (Send to Head of Dept)
                Employee emp = BusinessLogic.GetDeptHeadByDeptID(e.DepartmentID);
                Email email;
                String emailaddress;
                string emailname;
                String bodytext;
                String subject = "Requisition for Approval";

                emailaddress = emp.EmailAdd;
                emailname = emp.EmployeeName;
                bodytext = "Dear " + emailname + ",<br /><br />" + "There is a pending request waiting for your approval.<br /><br /><br /><br />================================================================<br /><br />This is a system generated email, Please do not reply. <br /><br />Store Administrator";
                email = new Email(emailaddress, subject, bodytext);
                BusinessLogic.SendEmail(email);

                //For Email notification (send to employee)                                
                subject = "Status of Requisition";

                emailaddress = e.EmailAdd;
                emailname = e.EmployeeName;
                bodytext = "Dear " + emailname + ",<br /><br />" + "Your request has been submitted and is awating approval.<br /><br /><br /><br />================================================================<br /><br />This is a system generated email, Please do not reply. <br /><br />Store Administrator";
                email = new Email(emailaddress, subject, bodytext);
                BusinessLogic.SendEmail(email);
            }
            //End creation

            //Update Begin
            String reqID2 = Request.Form["reqID"];
            int ReqID = Convert.ToInt16(reqID2);
            String itemcode = Request.Form["itemcode"];
            String qty2 = Request.Form["qty"];


            if (itemcode != null)
            {
                String[] ItemCode = itemcode.Split(',');
                String[] Qty2 = qty2.Split(',');

                for (int k = 0; k < ItemCode.Length; k++)
                {
                    int Quantity = Convert.ToInt16(Qty2[k]);

                    BusinessLogic.updateReqDetail(ReqID, ItemCode[k], Quantity);
                }

                //For Email notification (send to dept head)
                Employee emp = BusinessLogic.GetDeptHeadByDeptID(e.DepartmentID);
                Email email;
                String emailaddress;
                string emailname;
                String bodytext;
                String subject = "Updated Requisition for Approval";

                emailaddress = emp.EmailAdd;
                emailname = emp.EmployeeName;
                bodytext = "Dear " + emailname + ",<br /><br />" + "There is a pending updated request waiting for your approval.<br /><br /><br /><br />================================================================<br /><br />This is a system generated email, Please do not reply. <br /><br />Store Administrator";
                email = new Email(emailaddress, subject, bodytext);
                BusinessLogic.SendEmail(email);

                //For Email notification (send to employee)                                
                subject = "Status of Updated Requisition";

                emailaddress = e.EmailAdd;
                emailname = e.EmployeeName;
                bodytext = "Dear " + emailname + ",<br /><br />" + "Your updated request has been submitted and is awating approval.<br /><br /><br /><br />================================================================<br /><br />This is a system generated email, Please do not reply. <br /><br />Store Administrator";

Team1LUSS/Views/Requisition/ClerkReqDetails.cshtml
@{
    ViewBag.Title = "Approved Requisition Details";
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="../../plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>

<body class="theme-blue">
    @Html.Partial("_NavBar")
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="body">
                    <ol class="breadcrumb">
                        <li><a href="@Url.Action("ClerkReq", "Requisition")">Requisition Forms</a></li>
                        <li class="active">Requisition Form: @ViewBag.ReqDetails[0].RequisitionID</li>
                    </ol>
                </div>
            </div>

            <!-- Hover Rows -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">

                        <div class="header">
                            <h2>
                                Requisition Form Details
                            </h2>
                            @{var i = ViewBag.ReqDetails[0];
                                <p>
                                    Requisition ID: @i.RequisitionID <br>
                                    Submission Date: @string.Format("{0:d}", @i.Requisition.Date)<br>
                                    Employee: @i.Requisition.Employee1.EmployeeName<br>
                                </p>
                            }
                        </div>
                        <div class="body table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Description</th>
                                        <th>Quantity</th>                                        
                                        <th>Unit of Measurement</th>
                                        <th>Outstanding Disbursed Quantity</th>
                                        <th>Disbursed Quantity</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var req in ViewBag.ReqDetails)
                                    {
                                        int outstandingqty = req.ItemQty - req.DisbursedQty;
                                        <tr>
                                            <td>@req.Catalogue.Description</td>
                                            <td>@req.ItemQty</td>
                                            <td>@req.Catalogue.UnitofMeasure</td>
                                            <td>@outstandingqty</td>
                                            @*<td>@req.OutstandingQty</td>*@
                                            <td>@req.DisbursedQty</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
            <!-- #END# Hover Rows -->
        </div>
    </section>

    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="../../plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="../../plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <script src="../../js/pages/tables/jquery-datatable.js"></script>

    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>
</body>

</html>

Team1LUSS/Views/Requisition/DeptHeadReqDetails.cshtml
@{
    ViewBag.Title = "Requisition Details";
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="../../plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>

<body class="theme-blue">
    @Html.Partial("_NavBar")
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="body">
                    <ol class="breadcrumb">
                        <li><a href="@Url.Action("DeptHeadReqMain", "Requisition")">Non-Pending Forms</a></li>
                        <li class="active">Form: @ViewBag.ReqDetails[0].RequisitionID</li>
                    </ol>
                </div>
            </div>

            <!-- Hover Rows -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">

                        <div class="header">
                            <h2>
                                Requisition Form Details
                            </h2>
                            @{var i = ViewBag.ReqDetails[0];
                                <p>
                                    Requisition ID: @i.RequisitionID <br>
                                    Submission Date: @string.Format("{0:d}", @i.Requisition.Date)<br>
                                    Employee: @i.Requisition.Employee1.EmployeeName<br>
                                </p>
                            }
                        </div>
                        <div class="body table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Description</th>
                                        <th>Quantity</th>
                                        <th>Unit of Measurement</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var req in ViewBag.ReqDetails)
                                    {
                                        <tr>
                                            <td>@req.Catalogue.Description</td>
                                            <td>@req.ItemQty</td>
                                            <td>@req.Catalogue.UnitofMeasure</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
            <!-- #END# Hover Rows -->
            <!-- Basic Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Authorization
                            </h2>
                        </div>
                        <div class="body table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Status</th>
                                        <th>Deciding Authority</th>
                                        <th>Decision Date</th>
                                        <th>Comments</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{var a = ViewBag.ReqDetails[0];
                                        <tr>
                                            <td>@a.Requisition.Status</td>
                                            <td>@a.Requisition.Employee.EmployeeName</td>
                                            <td>@string.Format("{0:d}", @a.Requisition.AuthorizedDate)</td>
                                            <td>@a.Requisition.Comment</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Table -->


        </div>
    </section>

    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="../../plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="../../plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <script src="../../js/pages/tables/jquery-datatable.js"></script>

    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>
</body>

</html>

Team1LUSS/Views/Requisition/EmployeeReqDetail.cshtml
@{
    ViewBag.Title = "Employee Requisition Details";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />
    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />
    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">
    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>
<body class="theme-blue">
    @Html.Partial("_NavBar")
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <ol class="breadcrumb">
                    <li><a href="@Url.Action("EmployeeReq", "Requisition")">Requisition Form</a></li>
                    <li class="active">@ViewBag.rlist[0].RequisitionID</li>
                </ol>
            </div>
            <div class="block-header">
                <h2>Requisition Details</h2>
            </div>
            <br>
            <strong> Date: #@ViewBag.r.Date</strong>
        </div>

        <!-- Basic Examples -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="body">

                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                <thead>
                                    <tr>
                                        <th>Category</th>
                                        <th>Description</th>
                                        <th>Item Quantity</th>                                        
                                    </tr>
                                </thead>
                                <tfoot>

                                </tfoot>
                                <tbody>
                                    @foreach (var item in ViewBag.rlist)
                                    {
                                        <tr>
                                            <td>@item.Catalogue.Category.CategoryName</td>
                                            <td>@item.Catalogue.Description</td>
                                            <td>@item.OutstandingQty</td>                                            
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--Button-->
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" align="right">
            <a href="@Url.Action("EmployeeReq", "Requisition")" button type="button" class="btn btn-primary waves-effect">
                Back
            </a>
            &nbsp;&nbsp;&nbsp;&nbsp;
            @if (ViewBag.r.Status != "Approved")
            {

                <a href="@Url.Action("EmployeeReqEdit", "Requisition")/@ViewBag.r.RequisitionID" button type="button" class="btn btn-primary waves-effect">
                    Edit
                </a>
            }
        </div>


        <!-- button end -->
        <br />


    </section>

    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>
    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>
    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>

    <!-- Autosize Plugin Js -->
    <script src="../../plugins/autosize/autosize.js"></script>
    <!-- Moment Plugin Js -->
    <script src="../../plugins/momentjs/moment.js"></script>
    <!-- Jquery DataTable Plugin Js -->
    <script src="../../plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="../../plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <script src="../../js/pages/tables/jquery-datatable.js"></script>
    <script src="../../js/pages/forms/basic-form-elements.js"></script>

    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>
</body>
</html>