Team1LUSS/Models/RequisitionDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1LUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionDetail
    {
        public int RequisitionDetailID { get; set; }
        public Nullable<int> RequisitionID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<int> OutstandingQty { get; set; }
        public Nullable<int> DisbursedQty { get; set; }
        public Nullable<int> DisbursementID { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Disbursement Disbursement { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}

Team1LUSS/Models/Retrieval.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1LUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retrieval
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Retrieval()
        {
            this.RetrievalDetails = new HashSet<RetrievalDetail>();
        }
    
        public int RetrievalID { get; set; }
        public Nullable<int> ByClerkID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetrievalDetail> RetrievalDetails { get; set; }
    }
}

Team1LUSS/Controllers/RetrievalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Team1LUSS.Models;

namespace Team1LUSS.Controllers
{
    public class RetrievalController : Controller
    {
        // GET: Retrieval
        public ActionResult StockRetrievalMain()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID != 3)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE
            ViewBag.user = e;

            //Creation of Retrieval
            string s = Request.Form["itemcode"];
            if (s != null)
            {
                string sqty = Request.Form["qty"];
                int rid = BusinessLogic.InsertRetrieval(e.EmployeeID);
                for (int i = 0; i < s.Split(',').Count(); i++)
                {
                    BusinessLogic.InsertRetrievalDetail(rid, s.Split(',')[i], Convert.ToInt32(sqty.Split(',')[i]));
                    BusinessLogic.UpdateInterimRetrievalStockItemForRetrieval(s.Split(',')[i], Convert.ToInt32(sqty.Split(',')[i]));
                }
            }
            //Retrieval from Retrieval
            string ri = Request.Form["rdid"];
            if (ri != null)
            {
                string qty = Request.Form["QtyCollected"];
                for (int i = 0; i < ri.Split(',').Count(); i++)
                {
                    //Update Retrieval Item
                    BusinessLogic.UpdateRetrievalItemCollected(Convert.ToInt32(ri.Split(',')[i]), Convert.ToInt32(qty.Split(',')[i]));
                    //Update Interim Stock Item
                    ViewBag.ritem = BusinessLogic.getRetrievalItem(Convert.ToInt32(ri.Split(',')[i]));
                    int diff = Convert.ToInt32(ViewBag.ritem.QtyNeeded) - Convert.ToInt32(qty.Split(',')[i]);
                    BusinessLogic.UpdateInterimRetrievalStockItemFromDisbursement(ViewBag.ritem.ItemCode, diff);
                    //Update Retrieval Form
                    BusinessLogic.UpdateRetrievalStatus(Convert.ToInt32(Request.Form["rid"]), "Retrieved");
                }
            }
            ViewBag.rplist = BusinessLogic.listRetrievalPending();
            return View();
        }


        public ActionResult StockRetrievalDetail()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID != 3)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE
            ViewBag.user = e;
            //list view of Retrieval Details
            int rid = 0; ;
            if (Request.Form["rid"] != null)
            {
                rid = Convert.ToInt32(Request.Form["rid"]);
            }
            else if (Request.QueryString["rid"] != null)
            {
                rid = Convert.ToInt32(Request.QueryString["rid"]);
            }
            ViewBag.rdd = BusinessLogic.getRetrievalByID(rid);
            ViewBag.rdlist = BusinessLogic.listRetrievalDetailByID(rid);
            RetrievalDetail r = new RetrievalDetail();
            ViewBag.ritem = r;
            //View Retrieval Item
            if (Request.QueryString["retDID"] != null)
            {
                int retDId = Convert.ToInt32(Request.QueryString["retDID"]);
                ViewBag.ritem = BusinessLogic.getRetrievalItem(retDId);
                ViewBag.CQty = Convert.ToInt32(Request.QueryString["qty"]);
                String itemcode = ViewBag.ritem.ItemCode;
            }
            //Update Retrieval Item
            if (Request.Form["Qty"] != null)
            {
                string itemcode = Request.Form["itemcode"];
                int retDId = Convert.ToInt32(Request.Form["retDID"]);
                int actQty = Convert.ToInt32(Request.Form["Qty"]);
                //Update Interim Stock Item
                int diff = 0;
                if (ViewBag.ritem.Status == "Collected")
                { diff = Convert.ToInt32(ViewBag.ritem.ActualQty) - actQty; }
                else if (ViewBag.ritem.Status != "Collected")
                { diff = Convert.ToInt32(ViewBag.ritem.QtyNeeded) - actQty; }
                BusinessLogic.UpdateInterimRetrievalStockItemFromDisbursement(itemcode, diff);
                //Update Adjustment Voucher
                string y = Request.Form["AdjQty"];
                if (y != "")
                {
                    int AdjQty = Convert.ToInt32(y);
                    if (AdjQty != 0)
                    {
                        String pom = Request.Form["pom"];
                        String reason = Request.Form["reason"];
                        BusinessLogic.InsertAdjustmentVoucher(itemcode, pom, AdjQty, reason, e.EmployeeID);
                    }
                }
                //Update Retrieval Item 
                BusinessLogic.UpdateRetrievalItemCollected(retDId, actQty);
            }
            return View();
        }
        public ActionResult StockRetrievalDisbursement()
        {
            //EVERYPAGE
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            Employee e = (Employee)Session["user"];
            if (e.RoleID != 3)
            {
                return RedirectToAction("NotAuthorized");
            }
            //EVERYPAGE
            ViewBag.user = e;
            string s = "";
            //Display Retrieval info from main list
            if (Request.QueryString["rid"] != null)
            {
                s = Request.QueryString["rid"];
                BusinessLogic.UpdateRetrievalStatus(Convert.ToInt32(s), "Distributing");//lock retrieval list
            }
            //Information from Stock Retrieval Disbursement Detail
            else if (Request.Form["rid"] != null)
            {
                s = Request.Form["rid"];//retrieval Id
                string itemc = Request.Form["itemcode"];
                string rdid = Request.Form["rdid"];//RetrievalDetailId
                String dqty = Request.Form["disbursedQty"];  //disbursed qty for requisition item
                if (dqty != null)
                {
                    string reqdid = Request.Form["reqdid"];//get string of requisiton detailIDs
                    for (int i = 0; i < reqdid.Split(',').Count(); i++)//for every Requisition item
                    {
                        int reqDID = Convert.ToInt32(reqdid.Split(',')[i]);
                        int Dqty = Convert.ToInt32(dqty.Split(',')[i]);
                        ViewBag.reqitem = BusinessLogic.getRequisitionDetailItem(reqDID); //get the requisition item
                        if (Dqty != 0)
                        {
                            //Update Disbursement
                            ViewBag.Ditem = BusinessLogic.getDisbursementByDept(ViewBag.reqitem.Requisition.Employee1.DepartmentID); //find Disbursement form by Department ID (from requisition)
                            if (ViewBag.Ditem != null)//yes, there is Disbursement Form
                            {
                                ViewBag.DDitem = BusinessLogic.getDisbursementDetailItem(Convert.ToInt32(ViewBag.Ditem.DisbursementID), itemc);
                                if (ViewBag.DDitem != null)
                                {
                                    BusinessLogic.UpdateDisbursementDetailItem(Convert.ToInt32(ViewBag.DDitem.DisbursementDetailID), Dqty);
                                }
                                else if (ViewBag.DDitem == null)
                                {
                                    BusinessLogic.InsertDisbursementDetail(Convert.ToInt32(ViewBag.Ditem.DisbursementID), itemc, Dqty);
                                }
                            }
                            if (ViewBag.Ditem == null)//No, do not have Disbursment Form
                            {
                                BusinessLogic.InsertDisbursement(ViewBag.reqitem.Requisition.Employee1.DepartmentID, Convert.ToInt32(ViewBag.reqitem.RequisitionID), e.EmployeeID);
                                ViewBag.Ditem = BusinessLogic.getDisbursementByDept(ViewBag.reqitem.Requisition.Employee1.DepartmentID);
                                int did = Convert.ToInt32(ViewBag.Ditem.DisbursementID);
                                BusinessLogic.InsertDisbursementDetail(did, itemc, Dqty);
                            }
                            //Update Requisition item
                            BusinessLogic.UpdateRequisitionItem(reqDID, Dqty, Convert.ToInt32(ViewBag.Ditem.DisbursementID));
                            ViewBag.reqDlist = BusinessLogic.listRequisitionDetailByID(Convert.ToInt32(ViewBag.reqitem.RequisitionID));
                            //Update Requsition Status
                            foreach (var item in ViewBag.reqDlist)
                            {
                                if (item.OutstandingQty != 0)
                                {
                                    BusinessLogic.UpdateRequisitionStatus(Convert.ToInt32(item.RequisitionID), "Partially Fulfilled");
                                    break;
                                }
                                else if (item.OutstandingQty == 0)
                                { BusinessLogic.UpdateRequisitionStatus(Convert.ToInt32(item.RequisitionID), "Fulfilled"); }
                            }

                        }
                    }
                }
                BusinessLogic.UpdateRetrievalItemDisbursed(rdid); //update retrieval item
            }
            ViewBag.ritem = BusinessLogic.getRetrievalByID(Convert.ToInt32(s));

Team1LUSS/Views/Retrieval/StockRetrievalDetailCompleted.cshtml
@{
    ViewBag.Title = "Completed Stock Retrieval Details";
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>

<body class="theme-blue">
    @Html.Partial("_NavBar")
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <ol class="breadcrumb">
                    <li><a href="@Url.Action("StockRetrievalCompleted", "Retrieval")">Completed Stock Retrieval List</a></li>
                    <li class="active">Requisition List - @ViewBag.rdd.RetrievalID</li>
                </ol>
            </div>
            <!-- Requisition Form -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                           
                            <div class="row">

                                <h2>
                                    Requisition List - #@ViewBag.rdd.RetrievalID
                                </h2>
                            </div>
                            <br/>
                            <div class="row">
                                <h2>Date  @string.Format("{0:dd/MM/yyyy}", @ViewBag.rdd.Date)</h2>
                            </div>
                        </div>
                       
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>Item Code</th>
                                            <th>Description</th>
                                            <th>Quantity Needed</th>
                                            <th>Quantity Retrieved</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Item Code</th>
                                            <th>Description</th>
                                            <th>Quantity Needed</th>
                                            <th>Quantity Retrieved</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in ViewBag.rdlist)
                                        {
                                            <tr>
                                                <td>@item.ItemCode</td>
                                                <td>@item.Catalogue.Description</td>
                                                <td>@item.QtyNeeded</td>
                                                <td>@item.ActualQty</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# List of Retrieval List-->

        @*<div class="row">
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <button type="button" class="btn btn-primary waves-effect">Back</button>
            </div>
        </div>*@
        <br />

    </section>

    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>

    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <script src="../../js/pages/tables/jquery-datatable.js"></script>

    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="../../plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="../../plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

</body>

</html>

Team1LUSS/Views/Retrieval/StockRetrievalDisbursement.cshtml
@{
    ViewBag.Title = "Stock Retrieval Disbursement";
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title | Logic University Stationary Store Inventory System</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="../../plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="../../plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="../../plugins/animate-css/animate.css" rel="stylesheet" />

    <!-- Bootstrap Spinner Css -->
    <link href="../../plugins/jquery-spinner/css/bootstrap-spinner.css" rel="stylesheet">

    <!-- Custom Css -->
    <link href="../../css/style.css" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="../../css/themes/all-themes.css" rel="stylesheet" />
</head>

<body class="theme-blue">
    @Html.Partial("_NavBar")
    <section class="content">
        <div class="container-fluid">
            <form id="completeRetrieval" action="@Url.Action("StockRetrievalCompleted", "Retrieval")" method="post">
                <!-- Retrieval Item List -->
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="card">
                            <div class="header">
                                <div class="row">
                                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                        <h2>
                                            Retrieval Form - # @ViewBag.ritem.RetrievalID <input type="hidden" name="rid" value="@ViewBag.ritem.RetrievalID" />
                                        </h2>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    </div>
                                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                      <button type="button" class="btn btn-primary waves-effect" onclick="submitForm()" value="Submit form">Submit</button>
                                          
                                    </div>

                                </div>
                            </div>

                            <div class="body">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                        <thead>
                                            <tr>
                                                <th>Item Code</th>
                                                <th>Description</th>
                                                <th>Quantity Collected</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr>
                                                <th>Item Code</th>
                                                <th>Description</th>
                                                <th>Quantity Collected</th>
                                                <th>Status</th>
                                            </tr>
                                        </tfoot>
                                        <tbody>
                                            @foreach (var item in ViewBag.rdlist)
                                            {
                                                <tr>
                                                    <td>@if (item.Status == "Collected")
                                                    {<a href="@Url.Action("StockRetrievalDisbursementDetail", "Retrieval")?itemcode=@item.ItemCode&rdid=@item.RetrievalDetailID&retQty=@item.ActualQty">@item.ItemCode</a>}
                                                    else if (item.Status == "Disbursed") {@item.ItemCode }</td>
                                                    <td> @item.Catalogue.Description </td>
                                                    <td> @item.ActualQty </td>
                                                    <td> @item.Status <input type="hidden" class="status" value ="@item.Status" /></td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <!-- #END# Retrieval Item List -->
    </section>
   
     <!--JavaScript-->
    <script>
        function submitForm()
        {
            var item = 0;
            for (var i = 0; i < document.getElementsByClassName("status").length; i++)
            {
                if (document.getElementsByClassName("status")[i].value == "Disbursed")
                { item++; }
            }
            if (item == document.getElementsByClassName("status").length)
            {
                document.getElementById("completeRetrieval").submit();
            }
            else if (item != document.getElementsByClassName("status").length)
            { alert("Please disburse all items before submitting form."); }
        }
    </script>

    <!-- Jquery Core Js -->
    <script src="../../plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core Js -->
    <script src="../../plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Select Plugin Js -->
    <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="../../plugins/node-waves/waves.js"></script>

    <!-- Custom Js -->
    <script src="../../js/admin.js"></script>
    <script src="../../js/pages/tables/jquery-datatable.js"></script>

    <!-- Jquery Spinner Plugin Js -->
    <script src="../../plugins/jquery-spinner/js/jquery.spinner.js"></script>

    <!-- Demo Js -->
    <script src="../../js/demo.js"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="../../plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="../../plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="../../plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

</body>

</html>